jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/anoaky/comp550-project.git
  TrainBart:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |
        cd /inputs/repo
        pip install -r requirements.txt
        python bart.py -n sbf-bart-offensive -p offensive
      image: pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel